### ISSUE TITLE
TODO list (api)

### ISSUE THREAD

**Issue by sakura0711** [sakura0711/test-express-server#1]
## Story api 📖 
- [x]  /getAllStory     : to get all Story 
- [ ]  /getOneStory  : use ChapterID get one Story 
- [x]  /addStory        : add new Story 
- [x]  /putStory         : use ChapterID to modify Story 
- [x]  /delStory         : use ChapterID to delete one Story 

## Weapons api 🔫 
- [x]  /getAllWeapon : to get all Weapons 
- [ ]  /getOneWeapon : use WeaponID get one Weapon
- [x]  /addWeapon : add new Weapon
- [x]  /putWeapon : use WeaponID to modify Weapons
- [x]  /delWeapon : use WeaponID to delete one Weapon

## Attackskills api ⚔️
- [x]  /getAllAttackskill : to get all Attackskills 
- [ ]  /getOneAttackskill : use SkillID get one Attackskill
- [x]  /addAttackskill : add new Attackskill
- [x]  /putAttackskill : use SkillID to modify Attackskill
- [x]  /delAttackskill : use SkillID to delete one Attackskill

## Defenseskills api 🛡️
- [x]  /getAllDefenseskill : to get all defenseskill
- [ ]  /getOneDefenseskill : use SkillID get one defenseskill
- [x]  /addDefenseskill : add new defenseskill
- [x]  /putDefenseskill : use SkillID to modify defenseskill
- [x]  /delDefenseskill : use SkillID to delete one defenseskill

## Supportskill api ⛨
- [x]  /getAllSupportskill : to get all supportskill
- [ ]  /getOneSupportskill : use SkillID get one supportskill
- [x]  /addSupportskill : add new supportskill
- [x]  /putSupportskill : use SkillID to modify supportskill
- [x]  /delSupportskill : use SkillID to delete one supportskill

## PlayerInfo api 🎅
- [x]  /getAllPlayer: to get all Player
- [ ]  /getOnePlayer : use PlayerUUID get one Player
- [x]  /addPlayerl : add new supportskill
- [x]  /putPlayer : use PlayerUUID to modify Player
- [x]  /delPlayer : use PlayerUUID to delete one Player
